services:
  postgres:
    image: postgres:16-alpine
    container_name: tampakan-tcc-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: tampakan
      POSTGRES_PASSWORD: tampakan_dev
      POSTGRES_DB: tampakan_tcc
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
